Fix blocking and sneaking
nekkan/old-animations pull request #10
Opened 2021-05-20 09:47 UTC by TheKodeToad

Fixes blocking (at least in my opinion) - it now only works when holding a shield and hides the shield. This is to make it more suited for 1.16 servers - normally with this mod you can only block without a shield, and it doesn't reduce damage (it only reduces the player's speed). Even on 1.8 servers when blocking with this mod, the blocking animation only appears for less than a second before the server simulates blocking by giving you a shield, which then stops the animation.

For old sneaking, the smoothness is only removed when sneaking, but the animation is still shown when unsneaking. I fixed this by always removing the animation (I could have redirected the `lerp` (linear interpolate) function, but that doesn't work with the `OldAnimationsFeature` interface).

If I messed up parts of the code, let me know and I'll try to fix it, or the code can be edited by maintainers.

2021-05-20 10:14 UTC, nekkan requested changes

2021-05-20 10:14 UTC, nekkan commented on src/main/java/gq/nkkx/oldanimations/renderer/OldAnimationsHeldItemRenderer.java
> +            }
Here it would not be necessary to return, using this would be a better choice:
```java
        if (SwordBlockingFeature.isEnabled()) {
            if (SwordBlockingFeature.hasSwordAndShield(player)) {
                if (SwordBlockingFeature.isOffhand(player, item)) {
                    callbackInfo.cancel();
                    return;
                }
            if (SwordBlockingFeature.isSwordBlocking(player)) {
                ItemRenderingFeatureExecutionContext context = ItemRenderingFeatureExecutionContext.create(
                        callbackInfo, item, hand, new ItemRenderingMatrices(vertexConsumers, matrixStack),
                        new ItemRenderingProgress(swingProgress, equipProgress, tickDelta)
                );
                SwordBlockingFeature.LAZY.get().transform(context);
            }
        }
```

2021-05-20 10:14 UTC, nekkan commented on src/main/java/gq/nkkx/oldanimations/renderer/OldAnimationsThirdPersonItemRenderer.java
> +            }
Here the check is being repeated. I think it would be better to create a common method in the SwordBlockingFeature class and use it in both classes.

2021-05-20 10:14 UTC, nekkan commented on src/main/java/gq/nkkx/oldanimations/features/SwordBlockingFeature.java
> +        return livingEntity.getActiveItem().getItem() instanceof ShieldItem && livingEntity.isUsingItem();
Since these three methods are only being used in this class, I think it is better to leave it as non-static and set the visibility to `private`.

2021-05-20 10:16 UTC, nekkan commented on src/main/java/gq/nkkx/oldanimations/features/SwordBlockingFeature.java
> +        if (hasSwordAndShield(livingEntity)) {
It is a better alternative to check if the player is blocking the sword here than in the rendering class, since that is not the responsibility of that class.

2021-05-20 14:51 UTC, TheKodeToad commented
I've (hopefully) fixed everything.

Also, one of the most popular 1.7 animations is digging while using an item. Could that be implemented in the future?

2021-05-21 03:17 UTC, nekkan approved these changes

2021-05-21 03:18 UTC, nekkan commented
> I've (hopefully) fixed everything.
> 
> Also, one of the most popular 1.7 animations is digging while using an item. Could that be implemented in the future?

Of course! I plan to add it soon.

2021-05-21 03:18 UTC, merged